# 파일 위치: netlify.toml

[functions]
  directory = "netlify/functions"

# 'generateAvatar' 함수의 시간 제한을 20초로 늘립니다.
[functions."generateAvatar"]
  timeout = 20
  
[build]
  command = "npm run build"
  publish = "dist"
